### ISSUE TITLE
Create Docker container for application 

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/defundthepolice#11]
# What is the Task
Create a process that can build a docker image that contains all the data and the main_st.py

## Why do we want to do this
We want to be able to create a standalone container with all the components we want to host the application 

## How can I get started?
1. Create Dockerfile
2. Add all requirements needed to run the app
3. Create a build script
4. Run the image
5. Navigate to the localhost:8501 should see the application

## Definition of Done
Docker image created that can display the streamlit app

**Comment by dannylwe** [comment]
Hi, I would like to work on this for hacktoberfest

**Comment by banjtheman** [comment]
Awesome!! Post any questions in the comments

**Comment by raoashish10** [comment]
@dannylwe I would like to bring #12 to your attention as I think it would be important while creating the Docker file.

**Comment by Alig1493** [comment]
I would like to take up this task if no one else has taken it up.

**Comment by Alig1493** [comment]
Hello @banjtheman I added a PR for review #21
