### ISSUE TITLE
Error while installing requirements - pyarrow

### ISSUE THREAD

**Issue by raoashish10** [banjtheman/defundthepolice#12]
So I ran the command ```pip install -r requirements.txt``` but I ran into this error:
```
ERROR: Failed building wheel for pyarrow
  Running setup.py clean for pyarrow
Failed to build pyarrow
ERROR: Could not build wheels for pyarrow which use PEP 517 and cannot be installed directly
```
There seems to be some error with the pyarrow.

Platform: Windows 10, Using virtualenv
Python: 
Version 3.8.3
pip version: 20.2.3

Any idea as to how I can fix this error?

**Comment by raoashish10** [comment]
The error got fixed when I switched to Python 3.6
@banjtheman I saw that there was a task to make a Docker container for the application. I would suggest that the python version for the docker image be set to 3.6 so that build doesn't fail.
Closing this issue.

**Comment by banjtheman** [comment]
Hmm could just be a strange windows issue, I have Python 3.7.4 and able to build

https://discuss.streamlit.io/t/modulenotfounderror-no-module-named-pyarrow-lib-when-run-streamlit-hello/4622

**Comment by raoashish10** [comment]
@banjtheman Quite possible or I think it has got to do with python 3.8 but not sure though.
