### ISSUE TITLE
Data Collection D.C

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/defundthepolice#3]
# What is the Task

Collect budget data for Washington D.C

We would like to collect the following information for each county

state - State located 
county - Name of County ( can just be DC)
year - Year of budget
item - Budget item
budget - Ammount allocated to the item
source - Where data come from

After CSV has been created, place in the data folder

```
data//states/DC/COUNTY_NAME/budget.csv
```

## Why do we want to do this
We need the data in order to create meaningful messages 

## How can I get started?
I would begin by googling Washington D.C budget and begin compiling data into a CSV that can be used 

Here is an example of the CSV
https://raw.githubusercontent.com/banjtheman/defundthepolice/main/data/states/Virginia/Arlington/budget.csv

## Definition of Done
Data collected for Washington DC

**Comment by licaroline** [comment]
I'd like to work on this

**Comment by banjtheman** [comment]
Sure go for it

**Comment by banjtheman** [comment]
closed by #30
