### ISSUE TITLE
Create Docker image for API

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/defundthepolice#31]
# What is the Task
The API has lots of external dependencies, we need a docker image to easily stand up the service

## Why do we want to do this
To make it easy to stand up the API

## How can I get started?

- [ ] Create Dockerfile for API
  Requirements 
   * libpq-dev
   * python3
   * postgresql
   * gunicorn 
    * it should also add all the csvs in Data
- [ ] create a /health endpoint in the API that returns true
- [ ] Have the API read postgress url from ENV variable 
- [ ] The docker image should use gunicorn to start the server
- [ ] Have the API be on port 9000

## Definition of Done
1. Can start the docker image 
2. Do a curl localhost:9000/health 
3.  Get response of true True

**Comment by sambatlim** [comment]
Can I try?

**Comment by banjtheman** [comment]
sure go for it

**Comment by sambatlim** [comment]
> sure go for it

I need more detail on this issue. Could you explain me more about this issue?

**Comment by banjtheman** [comment]
Sure make a comment with any questions

**Comment by Rdroshan** [comment]
Can I help with a task here? I can see there are different levels for resolving this issue.

**Comment by friendofdog** [comment]
Is there room for more than one contributor? I've been working a lot on APIs in Flask lately.

**Comment by sambatlim** [comment]
> Can I help with a task here? I can see there are different levels for resolving this issue.

yes, welcome. we can work together. I am very new with devops.

**Comment by sambatlim** [comment]
> Is there room for more than one contributor? I've been working a lot on APIs in Flask lately.

yes, welcome. we can work together. I am very new with devops.

**Comment by Rdroshan** [comment]
Thanks, Let's divide the tasks. If you want I can help with dockerfile.

**Comment by friendofdog** [comment]
I can do these parts:

- [ ] create a /health endpoint in the API that returns true
- [ ] Have the API be on port 9000

@banjtheman Is this an internal API or will it be used to serve public REST endpoints? I ask because the app seems to run fine without the API. If you could give us a quick rundown, it would help.

**Comment by banjtheman** [comment]
> 
> 
> I can do these parts:
> 
>     * [ ]  create a /health endpoint in the API that returns true
> 
>     * [ ]  Have the API be on port 9000
> 
> 
> @banjtheman Is this an internal API or will it be used to serve public REST endpoints? I ask because the app seems to run fine without the API. If you could give us a quick rundown, it would help.

will be used for public rest endpoints
