### ISSUE TITLE
Create a Postgress DB Docker script

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/defundthepolice#32]
# What is the Task
Create a script that creates a Postgress Docker image with all the Data from the CSVs loaded

## Why do we want to do this
In order to have the data stored in a database, so we can more effectively query.

## How can I get started?
1.  Have a script pull a Postgres Docker image
2. Have the script create a new table called budget_data
3.  Have the script insert all the data from the CSVs into budget_data
4.  Perform a query on the table to ensure you can retrieve data.

## Definition of Done
1. Can run a script that stands up a Postgress database with all the data inserted
2. Can query the database and get results

**Comment by Jayzcool51** [comment]
I would like to contribute for this task. please assignee it to me.

**Comment by DaedalusG** [comment]
I'm also into this, it'd be my first Hacktoberfest, and open source contribution. Please assign me.

**Comment by banjtheman** [comment]
sure both of you can do this task

**Comment by SyahirahWanMin** [comment]
hi. please assign this task to me as well . Thanks would like to try a shot
