### ISSUE TITLE
Create folders for each state county pair

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/defundthepolice#4]
# What is the Task
Create a script to create a stub for each State and county for the data folder

## Why do we want to do this
To create a template for each of the counties

## How can I get started?
1. Need to find a list of all States and counites, I would look at the Census website for some data
https://www.census.gov/data.html

2. Using the data gathered create a script that can make directories in the data folder and create a .gitkeep file

```
data/STATE/COUNTY/.gitkeep
```

## Definition of Done
Each state and county folder is created in a reproducible script

**Comment by kunal266** [comment]
Is it a compulsion to use the given site link, or we can use our own ?

**Comment by banjtheman** [comment]
> 
> 
> Is it a compulsion to use the given site link, or we can use our own ?

No, if you can find the data elsewhere feel free to do so
