### ISSUE TITLE
Make Bar chart sorted

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/defundthepolice#42]
# What is the Task
Have the bar chart be sorted by the highest value.

## Why do we want to do this
To make the bar chart look better

## How can I get started?
1. Update code here to return a sorted var chart https://github.com/banjtheman/defundthepolice/blob/main/apps/viz.py#L33
2. Here is an example code of a sorted bar chart https://altair-viz.github.io/gallery/bar_chart_sorted.html

## Definition of Done
The bar chart image is sorted by highest first

**Comment by Medha08** [comment]
Hey, @banjtheman  Can I take up this issue?

**Comment by banjtheman** [comment]
> 
> 
> Hey, @banjtheman Can I take up this issue?

sure go for it

**Comment by Jayzcool51** [comment]
Can I create pull request for this?

**Comment by Medha08** [comment]
![Screenshot_20201006-053930](https://user-images.githubusercontent.com/6583928/95172947-a73aa900-07d5-11eb-97c8-f8b7c0e1df52.png)
Does this look good @banjtheman ?

**Comment by Medha08** [comment]
<img width="1440" alt="Screenshot 2020-10-06 at 5 27 32 AM" src="https://user-@banjtheman es.githubusercontent.com/6583928/95173199-fd0f5100-07d5-11eb-898e-6b3ff4bd3a54.png">
Does this look good? @banjtheman
