### ISSUE TITLE
Create a Stacked Bar Chart Visualization

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/defundthepolice#45]
# What is the Task
Create a streamgraph for the data

## Why do we want to do this
To have another viz

## How can I get started?
1. Add a new viz to https://github.com/banjtheman/defundthepolice/blob/main/apps/viz.py
2. Here is an example code of a steam graph https://altair-viz.github.io/gallery/streamgraph.html

## Definition of Done
Can select a streamgraph for the budget visualization

**Comment by taratip** [comment]
@banjtheman can I work on this issue?

**Comment by taratip** [comment]
I have a question regarding the graph. I understand that the y axis should be percent and it should show percent for each item in color. What would be the x axis?

**Comment by banjtheman** [comment]
Can use year

**Comment by taratip** [comment]
Currently there is only one year for each state so not sure how to plot it.

**Comment by banjtheman** [comment]
Good point lets pivot to a stacked bar chart


x-axis should be the sum of the percent
y-axis should be the source
and color should be the items

Example code
https://altair-viz.github.io/gallery/horizontal_stacked_bar_chart.html

![image](https://user-images.githubusercontent.com/696254/95389445-d595b280-08c1-11eb-99f1-1efd750f0202.png)
