### ISSUE TITLE
Budgets as a Service

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/defundthepolice#6]
# What is the Task
Can we create an API to get budget information?

## Why do we want to do this
To make our data more accessible
 
## How can I get started?
1. Have a way to convert CSV data into a database (Your choice for now)
2. Have code that can read from the database, and return JSON 
3. Grapql or REST ( We will want both eventually) 

## Definition of Done
Can make an API request to get budget data.

e.g
```
curl localhost:PORT/my_endpoint?my_parms=X
data returned based on my_params
```

**Comment by raoashish10** [comment]
Hey @banjtheman , I would like to work on this issue for hacktoberfest but can you specify the framework you guys intend to use for the API service?

**Comment by banjtheman** [comment]
> Hey @banjtheman , I would like to work on this issue for hacktoberfest but can you specify the framework you guys intend to use for the API service?

Python Flask

**Comment by raoashish10** [comment]
@banjtheman Sure that would be great! On it

**Comment by raoashish10** [comment]
@banjtheman I have some doubts regarding the logical structure of the API and forgive me if these questions are a little dumb but do I have to create endpoints for creating and inserting data in the tables too? Or do I only need to make an endpoint to retrieve data?

**Comment by banjtheman** [comment]
Yes have a function to load data, and a function to retrive data
Here's some pseudo code 

```
def load_data_from_csv(csv_path):
    csv = pd.read_csv(csv_path)
    load_data_into_db(csv)


@app.route('/data')
def get_data():
    state = request.args.get('state')
    budget =  request.args.get('budget')
    jsonResp = get_data_from_db(state,budget)
    return jsonResp
    

```

**Comment by raoashish10** [comment]
Okay! I have started working and my code is similar. I am trying to generalise the code so that on future additions of counties and states, there will be no hardcoding required.

**Comment by raoashish10** [comment]
@banjtheman I have a doubt. Will all counties have the same fields for their budgets (County Board, Management and Finance etc.)? Cause if so I will structure the database in that way instead of the way it is structured in the csv file

**Comment by banjtheman** [comment]
No, they won't have same field, but that doesn't matter since we are storing that information under "item"

Here are the lists of fields we are collecting for each county
```
state,county,year,item,budget,source
```

**Comment by thestrugglingblack** [comment]
@raoashish10 Hey can you assign yourself to this ticket? so other know that you are working on this feature. Thanks!

**Comment by raoashish10** [comment]
@banjtheman Okay! Understood

**Comment by banjtheman** [comment]
Todo 

- [x] create docker image #31 
- [x] create DB script #32 
- [x] Update docker.yml to start both api and database

**Comment by Alig1493** [comment]
@banjtheman a few queries regarding the budgets as a service:
* How do you want the app to behave overall, should this be internally dependent on the budgets service and fetch the data from there instead of fetching it from the csv as it does now?
* do you want to expose the api and make it publicly accessible?
* do you want the the app and api to start together or as separate services and connect internally using docker networks?

**Comment by banjtheman** [comment]
1.  For now the main app should be independent of the API
2.  In the future yes
3. Good point should have two docker compse files, one for the app, and another for the api. Will make a new ticket

**Comment by banjtheman** [comment]
Objectives complete, closing
