### ISSUE TITLE
Shapefiles for choropleth map

### ISSUE THREAD

**Issue by callumrollo** [banjtheman/defundthepolice#66]
# What is the Task
Dataset of county boundary shape files

## Why do we want to do this
To make a choropleth map (see Issue #47 )

## How can I get started?
Grab the counties shapefiles from [here](https://catalog.data.gov/dataset/tiger-line-shapefile-2017-nation-u-s-current-county-and-equivalent-national-shapefile) or another source you find.

## Definition of Done
Save shapefiles in a format usable in the map from Issue #47 and a reasonable size

**Comment by callumrollo** [comment]
Using geopandas to read the files, I get a csv that is ~ 200 Mb. Shapefiles are pretty high resolution. If we simplify boundaries (removing points) county boundaries will no longer perfectly align. This may or may not be an issue.

@banjtheman what is an appropriate size for the shapefiles?

**Comment by callumrollo** [comment]
Here's what I've got so far. Options for 200 Mb, 10 Mb and 2Mb

![image](https://user-images.githubusercontent.com/28703282/95567387-c9713880-0a1a-11eb-9c85-be4bac00e0c5.png)

**Comment by banjtheman** [comment]
Start with the 2 Mb one for now and see how that goes
