### ISSUE TITLE
Collect Fonts

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/defundthepolice#9]
# What is the Task
Currently, we only have one font for the social cards, we would like more.

## Why do we want to do this
To give users the ability to use more fonts

## How can I get started?
I would look for fonts online like at https://fonts.google.com/
And select the best-looking ones to add to the font folder.

## Definition of Done
At least 10 new fonts added to font folder

**Comment by debangeedas** [comment]
Hey! I would like to work on this!

**Comment by swastikchugh** [comment]
Hey @banjtheman , I would like to contribute to this.

**Comment by banjtheman** [comment]
Awesome, start going through fonts to add and download the .tff file for the fonts folder

**Comment by debangeedas** [comment]
Is there any way to ensure that the both of us do not end up adding the same fonts?

**Comment by banjtheman** [comment]
> Is there any way to ensure that the both of us do not end up adding the same fonts?

When you create your pull request, list the fonts you have collected, or leave a comment here to indicate what you have collected

**Comment by debangeedas** [comment]
I added the following 10 font families to the fonts folder:
CourierPrime, DancingScript, DavidLibre, Dosis, Epilogue, MiriamLibre, Oswald, Pacifico, Peddana, Raleway
I will create a PR on the 1st of October

**Comment by swastikchugh** [comment]
Im adding the following 10 font families:
Montserrat, NanumGothic, ZillaSlab, CormorantGaramond, PoiretOne, JosefinSlab, Armata, Jura, SairaSemiCondensed, CutiveMono
Ill also be creating a PR on the 1st of October.

**Comment by swastikchugh** [comment]
Hey @banjtheman 
Im getting permission denied error.

**Comment by debangeedas** [comment]
@banjtheman please accept my PR

**Comment by banjtheman** [comment]
Have enough fonts for now closing

**Comment by debangeedas** [comment]
@swastikchugh did the merging of the PR get reflected in your hacktoberfest page?

**Comment by swastikchugh** [comment]
Hey @debangeedas 
It is reflecting as a pr, but is currently in the 7 day maturity period.

**Comment by debangeedas** [comment]
Thanks for confirming!
